# -*- coding: utf-8 -*-
# Generated by Django 6.0.4 on 2026-04-30 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=120, unique=True)),
                ('ikon_slug', models.SlugField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ('isim',),
            },
        ),
        migrations.CreateModel(
            name='Mekan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=180)),
                ('aciklama', models.TextField(blank=True)),
                ('adres', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('web_sitesi', models.URLField(blank=True)),
                ('kapak_fotografi', models.ImageField(blank=True, upload_to='mekan_kapaklari/')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mekanlar', to='gurmerota.kategori')),
            ],
            options={
                'verbose_name': 'Mekan',
                'verbose_name_plural': 'Mekanlar',
                'ordering': ('isim',),
            },
        ),
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=180)),
                ('aciklama', models.TextField(blank=True)),
                ('baslangic_tarihi', models.DateTimeField()),
                ('bitis_tarihi', models.DateTimeField()),
                ('etkinlik_tipi', models.CharField(choices=[('konser', 'Konser'), ('tadim', 'Tadim'), ('festival', 'Festival'), ('atolye', 'Atolye'), ('diger', 'Diger')], default='diger', max_length=20)),
                ('gorsel', models.ImageField(blank=True, upload_to='etkinlik_gorselleri/')),
                ('mekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etkinlikler', to='gurmerota.mekan')),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ('-baslangic_tarihi',),
            },
        ),
    ]
