# -*- coding: utf-8 -*-
# Generated by Django 6.0.4 on 2026-04-30 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurmerota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.TextField()),
                ('puan', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlari', to=settings.AUTH_USER_MODEL)),
                ('mekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='gurmerota.mekan')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ('-olusturulma_tarihi',),
                'unique_together': {('mekan', 'kullanici')},
            },
        ),
    ]
