# Generated by Codex on 2026-04-30

from django.db import migrations


def seed_kategoriler(apps, _schema_editor):
    Kategori = apps.get_model("gurmerota", "Kategori")
    defaults = [
        ("Restoran", "restoran"),
        ("Kafe", "kafe"),
        ("Tatlici", "tatlici"),
        ("Firin", "firin"),
        ("Sokak Lezzeti", "sokak-lezzeti"),
    ]
    for isim, ikon_slug in defaults:
        Kategori.objects.get_or_create(
            isim=isim,
            defaults={"ikon_slug": ikon_slug},
        )


def reverse_seed_kategoriler(apps, _schema_editor):
    Kategori = apps.get_model("gurmerota", "Kategori")
    Kategori.objects.filter(
        isim__in=["Restoran", "Kafe", "Tatlici", "Firin", "Sokak Lezzeti"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("gurmerota", "0002_yorum"),
    ]

    operations = [
        migrations.RunPython(seed_kategoriler, reverse_seed_kategoriler),
    ]
