# Generated by Django 6.0.4 on 2026-05-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurmerota', '0003_seed_kategoriler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etkinlik',
        ),
    ]
