# -*- coding: utf-8 -*-
# Generated by Django 6.0.4 on 2026-05-04 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurmerota', '0004_delete_etkinlik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailKod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('kod', models.CharField(max_length=6)),
                ('amac', models.CharField(choices=[('verification', 'Dogrulama'), ('login', 'Giris')], max_length=20)),
                ('son_kullanma_tarihi', models.DateTimeField()),
                ('kullanildi', models.BooleanField(default=False)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_kodlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Kodu',
                'verbose_name_plural': 'Email Kodlari',
                'ordering': ('-olusturulma_tarihi',),
            },
        ),
    ]
