# -*- coding: utf-8 -*-
# Generated by GPT-5.2 on 2026-05-07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gurmerota", "0005_emailkod"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailKod",
        ),
    ]

