# -*- coding: utf-8 -*-
# Generated by GPT-5.2 on 2026-05-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gurmerota", "0006_delete_emailkod"),
    ]

    operations = [
        migrations.CreateModel(
            name="MekanFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="mekan_fotograflari/")),
                ("sira", models.PositiveIntegerField(default=0)),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "mekan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotograflar",
                        to="gurmerota.mekan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mekan Fotografi",
                "verbose_name_plural": "Mekan Fotografileri",
                "ordering": ("sira", "-olusturulma_tarihi"),
            },
        ),
    ]

