# Generated by GPT-5.2 on 2026-05-07

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("gurmerota", "0007_mekanfoto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favori",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorileri",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mekan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoriler",
                        to="gurmerota.mekan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favori",
                "verbose_name_plural": "Favoriler",
                "ordering": ("-olusturulma_tarihi",),
                "unique_together": {("kullanici", "mekan")},
            },
        ),
    ]

