# -*- coding: utf-8 -*-
# Generated by Django 6.0.4 on 2026-05-22 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurmerota', '0010_mekanfoto_turkce_adlandirma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favori',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorileri', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı'),
        ),
        migrations.AlterField(
            model_name='favori',
            name='mekan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriler', to='gurmerota.mekan', verbose_name='mekan'),
        ),
        migrations.AlterField(
            model_name='favori',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='ikon_slug',
            field=models.SlugField(blank=True, max_length=150, verbose_name='ikon etiketi'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='isim',
            field=models.CharField(max_length=120, unique=True, verbose_name='isim'),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='açıklama'),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='adres',
            field=models.CharField(max_length=255, verbose_name='adres'),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='isim',
            field=models.CharField(max_length=180, verbose_name='isim'),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='kapak_fotografi',
            field=models.ImageField(blank=True, upload_to='mekan_kapaklari/', verbose_name='kapak fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mekanlar', to='gurmerota.kategori', verbose_name='kategori'),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='enlem'),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='boylam'),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='telefon',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefon'),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='web_sitesi',
            field=models.URLField(blank=True, verbose_name='web sitesi'),
        ),
        migrations.AlterField(
            model_name='mekanfoto',
            name='image',
            field=models.ImageField(upload_to='mekan_fotograflari/', verbose_name='fotoğraf'),
        ),
        migrations.AlterField(
            model_name='mekanfoto',
            name='mekan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='gurmerota.mekan', verbose_name='mekan'),
        ),
        migrations.AlterField(
            model_name='mekanfoto',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='mekanfoto',
            name='sira',
            field=models.PositiveIntegerField(default=0, verbose_name='sıra'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlari', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='mekan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='gurmerota.mekan', verbose_name='mekan'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='puan',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='puan'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='yorum',
            field=models.TextField(verbose_name='yorum'),
        ),
    ]
