from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
)

from .forms import GirisFormu
from .views import (
    FavoriListApiView,
    FavoriToggleApiView,
    GirisApiView,
    KategoriDetailView,
    KategoriListView,
    KayitApiView,
    ProfilApiView,
    favori_toggle,
    favorilerim,
    MekanDetailView,
    MekanListView,
    home,
    kayit_ol,
    mekan_detay,
    mekan_duzenle,
    mekan_ekle,
    mekan_sil,
    meshur_lezzetler,
    profil,
    raporlar,
    rotam,
    SifreSifirlamaView,
    YorumListView,
)

urlpatterns = [
    path("", home, name="home"),
    path(
        "giris/",
        LoginView.as_view(template_name="registration/giris.html", authentication_form=GirisFormu),
        name="giris",
    ),
    path("kayit/", kayit_ol, name="kayit"),
    path("cikis/", LogoutView.as_view(next_page="home"), name="cikis"),
    path(
        "sifre-sifirla/",
        SifreSifirlamaView.as_view(),
        name="password_reset",
    ),
    path(
        "sifre-sifirla/gonderildi/",
        PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "sifre-sifirla/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path(
        "sifre-sifirla/tamamlandi/",
        PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("profil/", profil, name="profil"),
    path("raporlar/", raporlar, name="raporlar"),
    path("mekanlar/ekle/", mekan_ekle, name="mekan-ekle"),
    path("mekanlar/<int:pk>/", mekan_detay, name="mekan-detay"),
    path("mekanlar/<int:pk>/duzenle/", mekan_duzenle, name="mekan-duzenle"),
    path("mekanlar/<int:pk>/sil/", mekan_sil, name="mekan-sil"),
    path("favoriler/", favorilerim, name="favoriler"),
    path("rotam/", rotam, name="rotam"),
    path("lezzetler/", meshur_lezzetler, name="meshur-lezzetler"),
    path("mekanlar/<int:mekan_id>/favori-toggle/", favori_toggle, name="favori-toggle"),
    path("api/kategoriler/", KategoriListView.as_view(), name="kategori-list"),
    path("api/kategoriler/<int:pk>/", KategoriDetailView.as_view(), name="kategori-detail"),
    path("api/mekanlar/", MekanListView.as_view(), name="mekan-list"),
    path("api/mekanlar/<int:pk>/", MekanDetailView.as_view(), name="mekan-detail"),
    path("api/yorumlar/", YorumListView.as_view(), name="yorum-list"),
    path("api/auth/kayit/", KayitApiView.as_view(), name="api-kayit"),
    path("api/auth/giris/", GirisApiView.as_view(), name="api-giris"),
    path("api/auth/profil/", ProfilApiView.as_view(), name="api-profil"),
    path("api/favoriler/", FavoriListApiView.as_view(), name="api-favoriler"),
    path("api/mekanlar/<int:mekan_id>/favori/", FavoriToggleApiView.as_view(), name="api-favori-toggle"),
]
